Change_formal_parameter: Change_formal_parameter.o
	g++ -o Change_formal_parameter Change_formal_parameter.o

Change_formal_parameter.o: Change_formal_parameter.cpp
	g++ -c Change_formal_parameter.cpp

clean:
	rm -f *.o